"""
Django settings for toeic_score project.

Generated by 'django-admin startproject' using Django 4.1.
"""
import os
from pathlib import Path


#### -------------------------------------------------- ####
#### ---------------------- DIRS ---------------------- ####
#### -------------------------------------------------- ####

BASE_DIR = Path(__file__).resolve(strict=True).parent.parent


#### -------------------------------------------------- ####
#### ------------------- SECRET KEY ------------------- ####
#### -------------------------------------------------- ####

SECRET_KEY = "django-insecure-nia0!u+^u%e917w-gd5)93%2w&c!-8hl_0hy-01#2)e7cw7x9&"


#### -------------------------------------------------- ####
#### ------------------- DEBUG MODE ------------------- ####
#### -------------------------------------------------- ####

DEBUG = True


#### -------------------------------------------------- ####
#### ----------------- URLS/HOSTS/IPS ----------------- ####
#### -------------------------------------------------- ####

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]

INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]


#### -------------------------------------------------- ####
#### ------------------ APPLICATIONS ------------------ ####
#### -------------------------------------------------- ####

INSTALLED_APPS = [
    # Django applications
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Project applications

    # Third party applications
    'debug_toolbar'
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'


#### -------------------------------------------------- ####
#### ------------------ MIDDLEWARES ------------------- ####
#### -------------------------------------------------- ####

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    # Third party's middlewares
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]


#### -------------------------------------------------- ####
#### -------------------- ROOT URLS ------------------- ####
#### -------------------------------------------------- ####

ROOT_URLCONF = "toeic_score.urls"


#### -------------------------------------------------- ####
#### ------------------- CSRF TOKENS ------------------ ####
#### -------------------------------------------------- ####

CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True


#### ------------------------------------------------- ####
#### ------------------- TEMPLATES ------------------- ####
#### ------------------------------------------------- ####

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'templates', 'email_templates')
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


#### -------------------------------------------------- ####
#### ---------------------- WSGI ---------------------- ####
#### -------------------------------------------------- ####

WSGI_APPLICATION = "toeic_score.wsgi.application"


#### ------------------------------------------------- ####
#### ------------------- DATABASES ------------------- ####
#### ------------------------------------------------- ####

DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'toeic_score',
            'USER': 'yuhua',
            'PASSWORD': '526625',
            'HOST': 'localhost',
            'PORT': '5432',
            'TEST': {
                'NAME': 'test_01'
            }
        }
    }


#### ------------------------------------------------- ####
#### ----------- AUTHENTICATION PARAMETERS ----------- ####
#### ------------------------------------------------- ####

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


#### ------------------------------------------------- ####
#### ------------- INTERNATIONALIZATION -------------- ####
#### ------------------------------------------------- ####

LANGUAGE_CODE = 'fr'
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_L10N = True
USE_TZ = True


#### ------------------------------------------------- ####
#### ------------------ STATIC FILES ----------------- ####
#### ------------------------------------------------- ####

STATIC_URL = "static/"


#### ------------------------------------------------- ####
#### --------------- PRIMARY KEY FIELD --------------- ####
#### ------------------------------------------------- ####
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
